from google.adk.agents import Agent
from google.adk.tools import AgentTool
from google.cloud import bigquery
import os
import logging
import dotenv

dotenv.load_dotenv("../.env")

logger = logging.getLogger(__name__)
logger.setLevel(logging.INFO)


bq_client = bigquery.Client(location=os.environ["GOOGLE_CLOUD_LOCATION"])

PROJECT_ID      = os.environ["GOOGLE_CLOUD_PROJECT"]
SCORES_DATASET  = os.environ["BIGQUERY_SCORES_DATASET_ID"]   # contains student_scores, student_progress
CHAPTER_DATASET = os.environ["BIGQUERY_CHAPTER_DATASET_ID"]  # contains chapter_table

SCHEMA_CONTEXT = f"""
You have access to the following BigQuery tables.
Always filter by the student_id and subject_id provided to you.
Never query data for any other student.

TABLE: `{PROJECT_ID}.{SCORES_DATASET}.student_scores`
COLUMNS:
  - student_id                   STRING
  - subject_id                   STRING
  - timestamp                    TIMESTAMP
  - chapter_id                   STRING
  - subject_cumulative_progress  FLOAT
  - chapter_cumulative_progress  FLOAT

TABLE: `{PROJECT_ID}.{SCORES_DATASET}.student_progress`
COLUMNS:
  - student_id    STRING
  - subject_id    STRING
  - timestamp     TIMESTAMP
  - chapter_id    STRING
  - till_date_avg FLOAT
  - growth_delta  FLOAT

TABLE: `{PROJECT_ID}.{CHAPTER_DATASET}.chapter_table`
COLUMNS:
  - chapter_id   STRING
  - chapter_name STRING
  - subject_id   STRING

RULES:
  - Always include WHERE student_id = {{student_id}}
  - Weekday vs weekend: EXTRACT(DAYOFWEEK FROM timestamp)
    1=Sunday, 2=Monday ... 7=Saturday
    Weekday = DAYOFWEEK BETWEEN 2 AND 6
    Weekend = DAYOFWEEK IN (1, 7)
  - Monthly grouping: FORMAT_TIMESTAMP('%Y-%m', timestamp)
  - Never SELECT * — only relevant columns
  - Return at most 500 rows
  - Return ONLY the SQL query, nothing else
"""


text_to_sql_agent = Agent(
    model='gemini-2.5-flash',
    name='TextToSQLAgent',
    instruction=f"""
    You are a BigQuery SQL generation assistant.

    {SCHEMA_CONTEXT}

    You will receive a natural language question along with the {{student_id}} to filter on.

    Return ONLY the SQL query. No explanation, no markdown, no backticks.
    """,
)

text_to_sql_tool = AgentTool(agent=text_to_sql_agent)


def execute_sql(sql: str, tool_context) -> dict:
    """
    Executes a BigQuery SQL query generated by TextToSQLAgent.
    Validates that student_id is present before executing.
    """

    logger.info("execute_sql called with SQL: %s", sql)


    student_id = tool_context.state.get("student_id")

    

    if not student_id:
        return {"error": "student_id missing from session state."}

    if student_id not in sql:
        return {"error": "Query missing student_id filter. Refusing to execute."}

    try:
        results = bq_client.query(sql).result()
        rows = [dict(row) for row in results]

        return {
            "status":    "ok",
            "row_count": len(rows),
            "rows":      rows,
        }

    except Exception as e:
        return {"error": f"Query execution failed: {str(e)}"}