from google.adk.agents import Agent
from google.adk.tools import AgentTool
from google.cloud import bigquery

bq_client = bigquery.Client()

PROJECT_ID = "your-project-id"
DATASET_ID = "your-dataset-id"

SCHEMA_CONTEXT = f"""
You have access to the following BigQuery tables.
Always filter by the student_id and subject_id provided to you.
Never query data for any other student.

TABLE: `{PROJECT_ID}.{DATASET_ID}.student_scores`
COLUMNS:
  - student_id                   STRING
  - subject_id                   STRING
  - timestamp                    TIMESTAMP
  - chapter_id                   STRING
  - subject_cumulative_progress  FLOAT
  - chapter_cumulative_progress  FLOAT

TABLE: `{PROJECT_ID}.{DATASET_ID}.student_progress`
COLUMNS:
  - student_id    STRING
  - subject_id    STRING
  - timestamp     TIMESTAMP
  - chapter_id    STRING
  - till_date_avg FLOAT
  - growth_delta  FLOAT

TABLE: `{PROJECT_ID}.{DATASET_ID}.chapter_table`
COLUMNS:
  - chapter_id   STRING
  - chapter_name STRING
  - subject_id   STRING

RULES:
  - Always include WHERE student_id = '<value>' AND subject_id = '<value>'
  - Weekday vs weekend: EXTRACT(DAYOFWEEK FROM timestamp)
    1=Sunday, 2=Monday ... 7=Saturday
    Weekday = DAYOFWEEK BETWEEN 2 AND 6
    Weekend = DAYOFWEEK IN (1, 7)
  - Monthly grouping: FORMAT_TIMESTAMP('%Y-%m', timestamp)
  - Never SELECT * — only relevant columns
  - Return at most 500 rows
  - Return ONLY the SQL query, nothing else
"""


# dedicated SQL generation agent
text_to_sql_agent = Agent(
    model='gemini-3.1-pro',
    name='TextToSQLAgent',
    instruction=f"""
    You are a BigQuery SQL generation assistant.

    {SCHEMA_CONTEXT}

    You will receive a natural language question along with the student_id
    and subject_id to filter on.

    Return ONLY the SQL query. No explanation, no markdown, no backticks.
    """,
)


# wrap it as a tool so PerformanceAgent can call it
text_to_sql_tool = AgentTool(agent=text_to_sql_agent)


# execution tool — runs the SQL that TextToSQLAgent produced
def execute_sql(sql: str, tool_context) -> dict:
    """
    Executes a BigQuery SQL query generated by TextToSQLAgent.
    Validates that student_id is present before executing.
    """
    student_context = tool_context.state.get("student_context", {})
    student_id = student_context.get("student_id")

    if student_id not in sql:
        return {
            "error": "Query missing student_id filter. Refusing to execute.",
        }

    try:
        results = bq_client.query(sql).result()
        rows = [dict(row) for row in results]

        return {
            "status": "ok",
            "row_count": len(rows),
            "rows": rows,
        }

    except Exception as e:
        return {"error": f"Query execution failed: {str(e)}"}